INSERT INTO complaint (complaint_date, complaint_desc) VALUES
  ("Dec 6, 2020","Unspecified injury of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level"),
  ("Sep 21, 2019","Unspecified superficial injury of toes"),
  ("Dec 14, 2020","Laceration of other muscles, fascia and tendons at shoulder and upper arm level, unspecified arm"),
  ("May 22, 2019","Other hyperparathyroidism"),
  ("Dec 18, 2019","Corrosion of third degree of multiple sites of left wrist and hand"),
  ("Nov 21, 2019","Solitary bone cyst, left ulna and radius"),
  ("Apr 4, 2020","Adverse effect of antifungal antibiotics, systemically used"),
  ("Feb 28, 2019","Glycogen storage disease, unspecified"),
  ("Sep 30, 2021","Strain of unspecified muscle and tendon at ankle and foot level"),
  ("Mar 2, 2021","Exposure to smoke in uncontrolled fire in building or structure"),
  ("Sep 28, 2019","Adverse effect of antifungal antibiotics, systemically used"),
  ("Feb 29, 2020","Chronic postrheumatic arthropathy undefined, unspecified elbow"),
  ("Jun 21, 2019","Late syphilitic oculopathy"),
  ("Aug 13, 2020","Late syphilitic oculopathy"),
  ("Jan 10, 2019","Contusion of small intestine"),
  ("Feb 18, 2019","Other pneumothorax and air leak"),
  ("May 30, 2021","Injury of quadriceps muscle, fascia and tendon"),
  ("Oct 12, 2020","Syphilitic saddle nose"),
  ("Nov 26, 2019","Abrasion, unspecified foot"),
  ("Jul 13, 2021","Strain of unspecified muscle and tendon at ankle and foot level"),
  ("Aug 15, 2019","Acute embolism and thrombosis of right femoral vein"),
  ("Sep 20, 2020","Other bursitis of elbow"),
  ("Sep 18, 2020","Unspecified injury of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level"),
  ("Jul 21, 2021","Unspecified viral hepatitis C without hepatic coma"),
  ("Jan 27, 2019","Syphilitic saddle nose"),
  ("May 24, 2021","Unspecified pedal cyclist injured in collision with unspecified motor vehicles in nontraffic accident"),
  ("Jun 8, 2019","Other hammer toe(s) (acquired), left foot"),
  ("Dec 29, 2019","Late syphilitic oculopathy"),
  ("Nov 27, 2021","Exposure to smoke in uncontrolled fire in building or structure"),
  ("Jan 29, 2020","Chronic postrheumatic arthropathy undefined, unspecified elbow"),
  ("Sep 25, 2020","Salter-Harris Type III physeal fracture of upper end of humerus"),
  ("Sep 12, 2019","Contusion of small intestine"),
  ("Sep 29, 2021","Unspecified corneal deposit, unspecified eye"),
  ("Oct 14, 2020","Contusion of small intestine"),
  ("Mar 27, 2020","Other hammer toe(s) (acquired), left foot"),
  ("Jun 24, 2019","Pathological fracture, unspecified shoulder"),
  ("Jul 23, 2020","Unspecified superficial injury of toes"),
  ("May 17, 2020","Dysuria"),
  ("Mar 13, 2021","Glycogen storage disease, unspecified"),
  ("Dec 10, 2020","Mooren's corneal ulcer, unspecified eye"),
  ("Dec 9, 2019","Other specified injury of carotid artery"),
  ("Oct 20, 2021","Unspecified pedal cyclist injured in collision with unspecified motor vehicles in nontraffic accident"),
  ("Jul 19, 2020","Unspecified viral hepatitis C without hepatic coma"),
  ("Feb 15, 2019","Chondromalacia, left wrist"),
  ("May 21, 2021","Other hyperparathyroidism"),
  ("May 24, 2020","Nondisplaced fracture of anterior process of left calcaneus"),
  ("Nov 4, 2020","Laceration without foreign body of right back wall of thorax with penetration into thoracic cavity"),
  ("May 7, 2020","Pathological fracture, unspecified shoulder"),
  ("Jan 1, 2022","Abnormal hard tissue formation in pulp"),
  ("Feb 4, 2021","Other bursitis of elbow"),
  ("Dec 24, 2021","Other bursitis of elbow"),
  ("Dec 20, 2021","Glycogen storage disease, unspecified"),
  ("Jan 10, 2019","Contusion of small intestine"),
  ("Apr 9, 2019","Meningitis in Chagas' disease"),
  ("Jul 29, 2019","Other pneumothorax and air leak"),
  ("Jun 13, 2021","Burn of first degree of back of unspecified hand"),
  ("Jul 5, 2021","Glycogen storage disease, unspecified"),
  ("Jun 9, 2020","Other bursitis of elbow"),
  ("Jun 12, 2019","Unspecified pedal cyclist injured in collision with unspecified motor vehicles in nontraffic accident"),
  ("Jul 20, 2020","Unspecified viral hepatitis C without hepatic coma"),
  ("Nov 23, 2019","Unspecified viral hepatitis C without hepatic coma"),
  ("May 22, 2020","Unspecified corneal deposit, unspecified eye"),
  ("Jan 12, 2019","Other specified injury of carotid artery"),
  ("Sep 24, 2020","Other specified injury of carotid artery"),
  ("Dec 1, 2019","Calcific tendinitis, right lower leg"),
  ("Jan 4, 2019","Unspecified injury of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level"),
  ("Mar 10, 2021","Military operations involving flamethrower, civilian"),
  ("Aug 17, 2021","Acute embolism and thrombosis of right femoral vein"),
  ("Aug 19, 2020","Other hammer toe(s) (acquired), left foot"),
  ("Mar 4, 2019","Accident with wheelchair (powered)"),
  ("Apr 30, 2019","Acute petrositis, unspecified ear"),
  ("Jun 14, 2019","Salter-Harris Type III physeal fracture of upper end of humerus"),
  ("Feb 1, 2021","Unspecified corneal deposit, unspecified eye"),
  ("Jul 14, 2021","Laceration of other muscles, fascia and tendons at shoulder and upper arm level, unspecified arm"),
  ("Nov 9, 2021","Solitary bone cyst, left ulna and radius"),
  ("Jun 7, 2020","Unspecified injury of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level"),
  ("Feb 20, 2020","Late syphilitic oculopathy"),
  ("Sep 27, 2019","Other hyperparathyroidism"),
  ("Nov 6, 2019","Laceration without foreign body of back wall of thorax without penetration into thoracic cavity"),
  ("Mar 10, 2019","Adverse effect of antifungal antibiotics, systemically used"),
  ("Aug 4, 2021","Accident with wheelchair (powered)"),
  ("Jan 18, 2022","Salter-Harris Type III physeal fracture of upper end of humerus"),
  ("Jan 30, 2021","Salter-Harris Type III physeal fracture of upper end of humerus"),
  ("Jun 12, 2021","Nondisplaced fracture of anterior process of left calcaneus"),
  ("Aug 1, 2020","Meningitis in Chagas' disease"),
  ("Sep 20, 2019","Acute embolism and thrombosis of right femoral vein"),
  ("Feb 20, 2020","Unspecified injury of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level"),
  ("Nov 24, 2020","Accident with wheelchair (powered)"),
  ("Apr 5, 2019","Acute embolism and thrombosis of right femoral vein"),
  ("Aug 8, 2021","Glycogen storage disease, unspecified");